AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  FoodItemsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: MenuTable

  MenuFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: MenuTable
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetMenu:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /food-items
            Method: get
        AddMenu:
          Type: Api
          Properties:
            Path: /food-items
            Method: post
        UpdateMenu:
          Type: Api
          Properties:
           Path: /food-items/{id}
           Method: put
        DeleteMenu:
          Type: Api
          Properties:
            Path: /food-items/{id}
            Method: delete


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MenuApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  MenuFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt   MenuFunction.Arn
  MenuIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt   MenuFunctionRole.Arn
